version: "3.4"
    
services:

  postgresql:
    container_name: database
    image: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_USER=extreemedev
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=lunappark
    ports:
      - 5432:5432

  admin:
    container_name: admindb
    image: dpage/pgadmin4
    volumes:
      - admin_data:/var/lib/pgadmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=mattallev@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=example
    ports:
      - 80:80
    
      
volumes:
  pg_data: {}
  admin_data: {}


