version: "3.9"
    
services:

  nginx:
    container_name: sitoweb
    image: nginx:latest
    volumes:
      - type: bind
        source: /home/matt/app/linguaggiweb  #localhost
        target: /usr/share/nginx/html  #container
    ports:
      - "80:80"   #localhost:container
    restart: always

  pg:
    container_name: database
    image: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
      POSTGRES_DB: example
    ports:
      - 5432:5432

  admin:
    container_name: admindb
    image: dpage/pgadmin4
    volumes:
      - admin_data:/var/lib/pgadmin
    restart: always
    environment:
      - 'PGADMIN_DEFAULT_EMAIL=mattallev@gmail.com'
      - 'PGADMIN_DEFAULT_PASSWORD=example'
    ports:
      - 5050:80
    
      
volumes:
  pg_data: {}
  admin_data: {}


