version: "3.8"
    
services:

  web:
    depends_on:
      - database
    container_name: nginxphp
    image: webdevops/php-nginx:latest
    volumes:
      - ..:/app
    ports:
      - "80:80"
    restart: always

  database:
    container_name: postgres
    image: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=lunappark
    ports:
      - 5432:5432

  adminer:
    container_name: pgadmin
    image: dpage/pgadmin4
    volumes:
      - admin_data:/var/lib/pgadmin
      - ../database:/var/lib/pgadmin/storage # To ensure correct binding, execute the following command in the terminal: sudo chmod -R 777 database
    restart: always
    environment:
      #- PGADMIN_LISTEN_PORT=5050
      #- PGADMIN_CONFIG_SERVER_MODE=True
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=example
    ports:
      - 5050:80
    
      
volumes:
  pg_data: {}
  admin_data: {}

networks:
  default:
    name: lunappark_network
    driver: bridge

